routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/notifications', 'Admin\AdminNotificationController@getNotifications');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('checkrole')->group(function(){
	Route::post('/users/clearFilters', 'UserController@clearFilters')->name('users.clearFilters');
	Route::delete('/users/softDelete/{user}', 'UserController@softDelete')->name('users.softDelete');
	Route::put('/users/restore/{user}', 'UserController@restore')->name('users.restore');
	Route::resource('/users', 'UserController', ['except' =>['show', 'create', 'store']]); //

	Route::post('/avatars/clearFilters', 'AvatarsController@clearFilters')->name('avatars.clearFilters');
	Route::delete('/avatars/softDelete/{user}', 'AvatarsController@softDelete')->name('avatars.softDelete');
	Route::put('/avatars/restore/{user}', 'AvatarsController@restore')->name('avatars.restore');
	Route::resource('/avatars', 'AvatarsController');
	Route::put('/avatars/upload/{id}', 'AvatarsController@uploadFile')->name('avatars.uploaded');
	Route::post('/notifications/read', 'AdminNotificationController@markAsRead');
});

Route::namespace('User')->prefix('user')->name('user.')->middleware('checkroleprofile')->group(function(){
	Route::resource('/profiles', 'ProfilesController', ['except' =>['index', 'create', 'store', 'destroy']]);
	Route::get('/profiles/upload/{id}', 'ProfilesController@upload')->name('profiles.upload');
	Route::put('/profiles/upload/{id}', 'ProfilesController@uploadFile')->name('profiles.uploaded');

});

app/Avatar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Avatar extends Model
{
	use SoftDeletes; 
	
	protected $dates = ['deleted_at'];
	
    protected $fillable = [
        'display_name', 'original_name',
    ];
	
	public function user() {
		return $this->hasOne('App\User','avatar_id', 'id');
	}
	
}

app/Http/Controllers/Admin/AvatarsController.php
<?php


namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\Avatar;
use Session;
use Carbon\Carbon;
use Illuminate\Support\Facades\Validator;



class AvatarsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $listPage = 5;
        $avatars = Avatar::withTrashed();

        if ($request->has('originalName')) {
            $request->session()->put('Avatar.originalName', $request->get('originalName'));
        }
        if ($request->has('displayName')) {
            $request->session()->put('Avatar.displayName', $request->get('displayName'));
        }
        if ($request->has('createdAtFrom')) {
            $request->session()->put('Avatar.createdAtFrom', $request->get('createdAtFrom'));
        }
        if ($request->has('createdAtTo')) {
            $request->session()->put('Avatar.createdAtTo', $request->get('createdAtTo'));
        }
        if (!(empty($request->all()) && !$request->session()->get('Avatar'))) {
            $originalName = $request->session()->get('Avatar.originalName');
            $displayName = $request->session()->get('Avatar.displayName');
            $createdAtFrom = $request->session()->get('Avatar.createdAtFrom');
            $createdAtTo = $request->session()->get('Avatar.createdAtTo');
            if ($originalName) {
                $avatars = $avatars->where('original_name', 'like', "%$originalName%");
            }
            if ($displayName !== null) {
                $avatars = $avatars->where('display_name', 'like', "%$displayName%");
            }
            if ($createdAtFrom !== null) {
                $avatars = $avatars
                    ->where('created_at', '>=', Carbon::createFromFormat('Y-m-d', $createdAtFrom)->startOfDay()->toDateTimeString());
            }
            if ($createdAtTo !== null) {
                $avatars = $avatars
                    ->where('created_at', '<=', Carbon::createFromFormat('Y-m-d', $createdAtTo)->endOfDay()->toDateTimeString());
            }
        }
        $avatars = $avatars->orderBy('id', 'desc')->paginate($listPage);

        return View('admin.avatar.index')->with('avatars', $avatars);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Avatar $avatar)
    {
        return view('admin.avatar.edit')->with(['avatar' => $avatar]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Avatar $avatar)
    {
        $avatar->update(['original_name' => $request->originalName, 'display_name' => $request->displayName]);
        return redirect()->route('admin.avatars.index')->with('status', 'Edited avatar with id' . $avatar->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Avatar $avatar)
    {

        $avatar->user->roles()->detach();
        $avatar->user()->forceDelete();
        $avatar->forceDelete();
        return redirect()->route('admin.avatars.index')->with('status', 'Avatar with id ' . $avatar->id . ' was permanently deleted');
    }

    public function softDelete($id)
    {
        $avatar = Avatar::find($id);
        $avatar->user->roles()->detach();
        $avatar->user()->delete();
        $avatar->delete();
        return redirect()->route('admin.avatars.index')->with('status', 'Avatar with id ' . $avatar->id . ' was deleted');
    }

    public function restore($id)
    {

        $avatar = Avatar::withTrashed()->find($id);
        $avatar->restore();

        return redirect()->route('admin.avatars.index')->with('status', 'Avatar with id ' . $id . ' was restored');
    }

    public function clearFilters(Request $request)
    {
        Session::forget('Avatar');

        return redirect()->route('admin.avatars.index')->with(['status' => 'Filters Cleared']);
    }
	
	public function uploadFile(Request $request, $avatar)
    {	
		$validator = Validator::make($request->all(), [
			'newImage' => 'required|image',
		]);

		if($validator->fails()){
			return redirect()->route('admin.avatars.edit', $avatar)->with('error', 'Picture should be loaded');
		}
		
		$avatar = Avatar::find($avatar);
		if($file = $request->file('newImage')){
			$clientName = $file->getClientOriginalName();
			$name = pathinfo($file->store('public/uploaded'), PATHINFO_BASENAME);
			$avatar->update(['original_name' => $clientName, 'display_name' => $name]);
		}
		return redirect()->route('admin.avatars.edit', $avatar)->with('status', 'Uploaded file to user with id' . $avatar->id);
    }
}

resources/views/admin/avatar/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
							
        <div class="col-md-8">
			 
			<div class="row">
				<div class="col-md-3">
				<a href="{{ route('admin.avatars.index') }}" title="Back to list"><button class="btn btn-warning"><i class="fa fa-arrow-left" aria-hidden="true"></i> Go to avatar list</button></a>
				</div>
				<div class="col-md-3">
				<a href="{{ route('admin.users.edit', $avatar->user)}}"><button type="button" class="btn btn-success float-left">Go to user {{$avatar->user->id}}</button></a>
				</div>
			</div>
			
            <div class="card">

                <div class="card-header">Edit avatar {{$avatar->id}}</div>

                <div class="card-body">
					<form action="{{ route('admin.avatars.update', $avatar)}}" method="POST">
							@csrf
							{{method_field('PUT')}}				
                        <div class="form-group row">
                            <label for="displayName" class="col-md-4 col-form-label text-md-right">Display name</label>

                            <div class="col-md-6">
                                <input id="displayName" type="text" class="form-control @error('displayName') is-invalid @enderror" name="displayName" value="{{ $avatar->display_name }}" required  autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Original name</label>

                            <div class="col-md-6">
                                <input id="originalName" type="text" class="form-control @error('originalName') is-invalid @enderror" name="originalName" value="{{$avatar->original_name}}" required>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
						
						
						<button type="submit" class="btn btn-success">Update</button>
					</form>
                </div>
				<br>
				<div class="card">

					<div class="card-header">Upload image</div>

					<div class="card-body">
						@if (session('error'))
							<div class="alert alert-danger" role="alert">
								{{ session('error') }}
							</div>
						@endif
						@if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
						@endif
						<form action="{{ route('admin.avatars.uploaded', $avatar)}}" method="POST" enctype="multipart/form-data">
								@csrf
								{{method_field('PUT')}}				
							
							<div class="form-group row">
								<label for="name" class="col-md-4 col-form-label text-md-right">Upload new image</label>

								<div class="col-md-6">
									<input id="newImage" type="file" class="form-control-file" name="newImage">
								</div>
							</div>
							
							<button type="submit" class="btn btn-success">Update</button>
						</form>
						<br>
							<img src="{{ asset('storage/uploaded/' .$avatar->display_name) }}" width="400" height="235" style="margin:0 auto"/>
					</div>
				</div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/avatar/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row justify-content-center">
        <div class="col-md-11">
            <div class="card">
			  <div class="card-header">Filter</div>
			  <div class="card-body">
			  <form action="{{ route('admin.avatars.index')}}" method="GET">

                        <div class="form-group row">
                            <div class="col-md-4">
                                <label for="originalName" class="col-form-label text-md-right">Original name</label>
                                <input id="originalName" type="text" class="form-control" name="originalName" value="{{Request::session()->has('Avatar.originalName') ? Request::session()->get('Avatar.originalName') : ''}}">
                            </div>
							<div class="col-md-4">
                                <label for="dispalyName" class="col-form-label text-md-right">Dispaly name</label>
                                <input id="dispalyName" type="text" class="form-control" name="displayName" value="{{Request::session()->has('Avatar.displayName') ? Request::session()->get('Avatar.displayName') : ''}}" >
                            </div>
                            <div class="col-md-4">
                                <span class="input-group-addon">Created at</span>
                                <div class='form-group'>
                                    <label for="createdAtFrom" class="col-form-label text-md-right">Created from</label>
                                    <div class='input-group date'>
                                        {!! Form::date('createdAtFrom', Request::session()->get('Avatar.createdAtFrom') ?? null, ['id' => 'createdAtFrom', 'class' => 'form-control datepicker', 'data-date-format' => 'yyyy-mm-dd', 'placeholder' => 'Date from...']) !!}
                                    </div>
                                </div>
                                <div class='form-group'>
                                    <label for="createdAtTo" class="col-form-label text-md-right">Created to</label>
                                    <div class='input-group date'>
                                        {!! Form::date('createdAtTo', Request::session()->get('Avatar.createdAtTo') ?? null, ['id' => 'createdAtTo', 'class' => 'form-control datepicker', 'data-date-format' => 'yyyy-mm-dd', 'placeholder' => 'Date to...']) !!}
                                    </div>
                                </div>
                            </div>
                        </div>

						<div class="row justify-content-center">
							<button type="submit" class="btn btn-success">Filter</button>
						</div>
					</form>
					<form action="{{ route('admin.avatars.clearFilters')}}" method="post">
						<div class="row justify-content-center">
							<input type="submit"  class="btn btn-success btn-sm" value="Clear filter" />
						</div>
							@method('post')
							@csrf
					</form>
			  </div>
			</div>
		</div>
	</div>
    <div class="row justify-content-center">
        <div class="col-md-11">
            <div class="card">
                <div class="card-header">Avatars</div>

                <div class="card-body">
					@if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
					 @if (session('error'))
                        <div class="alert alert-danger" role="alert">
                            {{ session('error') }}
                        </div>
                    @endif

				 <table class='table'>
					<thead>
					<tr>
						<th scope="col">ID</th>
						<th colspan="1">User ID</th>
						<th colspan="1">Display name</th>
						<th colspan="1">Original name</th>
						<th colspan="1">Created at</th>
						<th colspan="1">Updated at</th>
						<th colspan="1">Deleted at</th>
						<th colspan="1">Actions</th>
					</tr>
					</thead>
					<tbody>
					@foreach($avatars as $avatar)
					@php $deleted = $avatar->deleted_at; @endphp
					<tr @if($deleted) class='bg-danger' @endif>
						<td>{{$avatar->id}}</td>
						<td>
							@php $user = $avatar->user; @endphp
							@if($user)
							<a href="{{ route('admin.users.edit', $avatar->user)}}"><button type="button" class="btn btn-success btn-sm float-left">Go to user {{$avatar->user->id}}</button></a>
							@endif
						</td>
						<td>{{$avatar->display_name}}</td>
						<td>{{$avatar->original_name}}</td>
						<td>{{$avatar->created_at}}</td>
						<td>{{$avatar->updated_at}}</td>
						<td>{{$avatar->deleted_at}}</td>
						<td>
						@if(!$deleted)
							<a href="{{ route('admin.avatars.edit', $avatar)}}"><button type="button" class="btn btn-success btn-sm float-left">Edit</button></a>
							<form action="{{route('admin.avatars.softDelete', $avatar)}}" method="post">
							<input type="submit" class="btn btn-danger btn-sm" value="Soft delete" />
							@method('delete')
							@csrf
							</form>
						@endif
							<form action="{{route('admin.avatars.destroy', $avatar)}}" method="post">
							<input type="submit"  class="btn btn-warning btn-sm" value="Hard Delete" />
							@method('delete')
							@csrf
							</form>
						@if($deleted)
							<form action="{{ route('admin.avatars.restore', $avatar )}}" method="post">
							<input type="submit"  class="btn btn-success btn-sm" value="Restore" />
							@method('put')
							@csrf
							</form>
						@endif
						</td>
					</tr>
					@endforeach

					</tbody>
				</table>
				{{ $avatars->links() }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection