routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::post('/notifications', 'Admin\AdminNotificationController@getNotifications');

Route::namespace('Admin')->prefix('admin')->name('admin.')->middleware('checkrole')->group(function(){
	Route::post('/users/clearFilters', 'UserController@clearFilters')->name('users.clearFilters');
	Route::delete('/users/softDelete/{user}', 'UserController@softDelete')->name('users.softDelete');
	Route::put('/users/restore/{user}', 'UserController@restore')->name('users.restore');
	Route::resource('/users', 'UserController', ['except' =>['show', 'create', 'store']]); //

	Route::post('/avatars/clearFilters', 'AvatarsController@clearFilters')->name('avatars.clearFilters');
	Route::delete('/avatars/softDelete/{user}', 'AvatarsController@softDelete')->name('avatars.softDelete');
	Route::put('/avatars/restore/{user}', 'AvatarsController@restore')->name('avatars.restore');
	Route::resource('/avatars', 'AvatarsController');
	Route::put('/avatars/upload/{id}', 'AvatarsController@uploadFile')->name('avatars.uploaded');
	Route::post('/notifications/read', 'AdminNotificationController@markAsRead');
});

Route::namespace('User')->prefix('user')->name('user.')->middleware('checkroleprofile')->group(function(){
	Route::resource('/profiles', 'ProfilesController', ['except' =>['index', 'create', 'store', 'destroy']]);
	Route::get('/profiles/upload/{id}', 'ProfilesController@upload')->name('profiles.upload');
	Route::put('/profiles/upload/{id}', 'ProfilesController@uploadFile')->name('profiles.uploaded');

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable;
	use SoftDeletes;

	protected $dates = ['deleted_at'];
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'active', 'avatar_id', 'lastlogin_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

	public function roles() {
		return $this->belongsToMany('App\Role');
	}

	public function avatar() {
		return $this->belongsTo('App\Avatar','avatar_id','id');
	}

	public function hasAnyRoles($roles) {
		if($this->roles()->whereIn('name', $roles)->first())
			return true;
		return false;
	}

	public function hasRole($role) {
		if($this->roles()->where('name', $role)->first())
			return true;
	}
    /**
     * The channels the user receives notification broadcasts on.
     *
     * @return string
     */
    public function receivesBroadcastNotificationsOn()
    {
        return 'channel.admin.' . $this->id;
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Illuminate\Http\Request;
use App\User;
use App\Role;
use Session;


class UserController extends Controller
{
	public function _construct()
	{
		$this->middleware('auth');
	}
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
		$listPage = 5;
		$users = User::withTrashed();

		if($request->has('name')) {
            $request->session()->put('User.name', $request->get('name'));
        }
		if($request->has('email')) {
			$request->session()->put('User.email', $request->get('email'));
        }
        if ($request->has('createdAtFrom')) {
            $request->session()->put('User.createdAtFrom', $request->get('createdAtFrom'));
        }
        if ($request->has('createdAtTo')) {
            $request->session()->put('User.createdAtTo', $request->get('createdAtTo'));
        }
        if ($request->has('updatedAtFrom')) {
            $request->session()->put('User.updatedAtFrom', $request->get('updatedAtFrom'));
        }
        if ($request->has('updatedAtTo')) {
            $request->session()->put('User.updatedAtTo', $request->get('updatedAtTo'));
        }
        if ($request->has('lastLoginAtFrom')) {
            $request->session()->put('User.lastLoginAtFrom', $request->get('lastLoginAtFrom'));
        }
        if ($request->has('lastLoginAtTo')) {
            $request->session()->put('User.lastLoginAtTo', $request->get('lastLoginAtTo'));
        }
        if ($request->has('active')) {
            $request->session()->put('User.active', $request->get('active'));
        }
		if(!(empty($request->all()) && !$request->session()->get('User'))) {

			$name = $request->session()->get('User.name');
			$email = $request->session()->get('User.email');
            $createdAtFrom = $request->session()->get('User.createdAtFrom');
            $createdAtTo = $request->session()->get('User.createdAtTo');
            $updatedAtFrom = $request->session()->get('User.updatedAtFrom');
            $updatedAtTo = $request->session()->get('User.updatedAtTo');
            $lastLoginAtFrom = $request->session()->get('User.lastLoginAtFrom');
            $lastLoginAtTo = $request->session()->get('User.lastLoginAtTo');
            $active = $request->session()->get('User.active');

			if($name !== null) {
                $users = $users->where('name','like',"%$name%");
			}
			if($email !== null) {
                $users = $users->where('email','like',"%$email%");
			}
            if($active !== null) {
                $users = $users->where('active','=',$active);
            }
            if ($createdAtFrom !== null) {
                $users = $users
                    ->where('created_at', '>=', Carbon::createFromFormat('Y-m-d', $createdAtFrom)->startOfDay()->toDateTimeString());
            }
            if ($createdAtTo !== null) {
                $users = $users
                    ->where('created_at', '<=', Carbon::createFromFormat('Y-m-d', $createdAtTo)->endOfDay()->toDateTimeString());
            }
            if ($updatedAtFrom !== null) {
                $users = $users
                    ->where('updated_at', '>=', Carbon::createFromFormat('Y-m-d', $updatedAtFrom)->startOfDay()->toDateTimeString());
            }
            if ($updatedAtTo !== null) {
                $users = $users
                    ->where('updated_at', '<=', Carbon::createFromFormat('Y-m-d', $updatedAtTo)->endOfDay()->toDateTimeString());
            }
            if ($lastLoginAtFrom !== null) {
                $users = $users
                    ->where('lastlogin_at', '>=', Carbon::createFromFormat('Y-m-d', $lastLoginAtFrom)->startOfDay()->toDateTimeString());
            }
            if ($lastLoginAtTo !== null) {
                $users = $users
                    ->where('lastlogin_at', '<=', Carbon::createFromFormat('Y-m-d', $lastLoginAtTo)->endOfDay()->toDateTimeString());
            }
		}

		$users = $users->orderBy('id', 'desc')->paginate($listPage);
        return View('admin.user.index')->with('users', $users);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::all();
		return view('admin.user.edit')->with(
		            ['user' => $user,
                     'roles' => $roles
	            	]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->roles()->sync($request->roles);
		$user->update(['name' => $request->name, 'email' => $request->email, 'active' => $request->active]);
		return redirect()->route('admin.users.index')->with('status', 'Edited user with id' . $user->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->roles()->detach();
		//$user->avatar()->forceDelete();
		$user->forceDelete();
		return redirect()->route('admin.users.index')->with('status', 'User with id ' . $user->id . ' was permanently deleted');
    }

	public function softDelete(User $user)
    {
		$user->update(['active' => 0]);
        $user->roles()->detach();
		$user->avatar()->delete();
		$user->delete();
		return redirect()->route('admin.users.index')->with('status', 'User with id ' . $user->id . ' was deleted');
    }

	public function restore($id){

		$user = User::withTrashed()->find($id);
		$user->restore();
		$user->avatar()->restore();
		$user->roles()->attach(Role::where('name', 'user')->first());

		return redirect()->route('admin.users.index')->with('status', 'User with id ' . $id . ' was restored');
	}

	public function clearFilters(Request $request)
	{
        Session::forget('User');

        return redirect()->route('admin.users.index')->with(['status' => 'Filters Cleared']);
	}
}

app/Http/Controllers/User/ProfilesController.php
<?php


namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\User;
use App\Role;
use App\Avatar;
use Illuminate\Support\Facades\Validator;

class ProfilesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return 'hh';
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($user)
    {	
		$user = User::find($user);
		return view('user.profile.show')->with(['user' => $user]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit( $user)
    {
		$user = User::find($user);
        return view('user.profile.edit')->with(['user' => $user]);
    }

	public function upload($user)
    {
		$user = User::find($user);
        return view('user.profile.uploadFile')->with(['user' => $user]);
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $user)
    {	
		$user = User::find($user);
        $user->update(['name' => $request->name, 'email' => $request->email]);
		$user->avatar()->update(['original_name' => $request->originalName]);
		return redirect()->route('user.profiles.show', $user)->with('status', 'Edited user with id' . $user->id);
    }

	public function uploadFile(Request $request, $user)
    {	
		$validator = Validator::make($request->all(), [
			'newImage' => 'required|image',
		]);

		if($validator->fails()){
			return redirect()->route('user.profiles.upload', $user)->with('error', 'Picture should be loaded');
		}
		
		$user = User::find($user);
		if($file = $request->file('newImage')){
			$clientName = $file->getClientOriginalName();
			$name = pathinfo($file->store('public/uploaded'), PATHINFO_BASENAME);
			$user->avatar()->update(['original_name' => $clientName, 'display_name' => $name]);
		}
		return redirect()->route('user.profiles.show', $user)->with('status', 'Uploaded file to user with id' . $user->id);
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">

        <div class="col-md-8">
			<div class="row">
				<div class="col-md-3">
				<a href="{{ route('admin.users.index') }}" title="Back to list"><button class="btn btn-warning"><i class="fa fa-arrow-left" aria-hidden="true"></i> Go to user list</button></a>
				</div>
				<div class="col-md-3">
				<a href="{{ route('admin.avatars.edit', $user->avatar)}}"><button type="button" class="btn btn-success float-left">Go to avatar {{$user->avatar->id}}</button></a>
				</div>
			</div>
            <div class="card">

                <div class="card-header">Edit user {{$user->name}}</div>

                <div class="card-body">
					<form action="{{ route('admin.users.update', $user)}}" method="POST">
							@csrf
							{{method_field('PUT')}}
                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email }}" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control @error('email') is-invalid @enderror" name="name" value="{{$user->name}}" required>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
						<div class="form-group row">
							<label for="roles" class="col-md-4 col-form-label text-md-right"> Roles </label>


								<div class="col-md-6">
									@foreach($roles as $role)

										<input type='checkbox' name='roles[]' value='{{$role->id}}'
										@if($user->roles->pluck('id')->contains($role->id)) checked @endif>
										<label>{{$role->name}}</label>
									@endforeach
								</div>
						</div>
						<div class="form-group row">
							<label for="active" class="col-md-4 col-form-label text-md-right"> Active </label>

								<div class="col-md-6">
										<input type='radio' name='active' value='1'
										@if($user->active === 1) checked @endif>
										<label>User is active</label>
										<input type='radio' name='active' value='0'
										@if($user->active === 0) checked @endif>
										<label>User is not active</label>
								</div>
						</div>

						<button type="submit" class="btn btn-success">Update</button>
					</form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-11">
                <div class="card">
                    <div class="card-header">Filter</div>
                    <div class="card-body">
                        <form action="{{ route('admin.users.index')}}" method="GET">

                            <div class="form-group row">

                                <div class="col-md-4">
                                    <label for="email"
                                           class="col-form-label text-md-right">{{ __('E-Mail Address') }}</label>
                                    <input id="email" type="text" class="form-control" name="email"
                                           value="{{Request::session()->has('User.email') ? Request::session()->get('User.email') : ''}}">
                                </div>
                                <div class="col-md-4">
                                    <label for="name" class="col-form-label text-md-right">Name</label>
                                    <input id="name" type="text" class="form-control" name="name"
                                           value="{{Request::session()->has('User.name') ? Request::session()->get('User.name') : ''}}">
                                </div>
                                <div class="col-md-4">
                                    <label for="name" class="col-form-label text-md-right">Active</label>
                                    <div class='input-group date'>
                                        {!! Form::select('active', ['' => 'Wybierz', '0' => 'Nieaktywny', '1' => 'Aktywny'], Request::session()->has('User.active') ? Request::session()->get('User.active') : null, ['class' => 'form-control selectpicker', 'id' => 'active']) !!}
                                    </div>
                               </div>
                           </div>
                           <div class="form-group row">
                               <div class="col-md-4">
                                   <div class='form-group'>
                                       <label for="createdAtFrom" class="col-form-label text-md-right">Created at
                                           from</label>
                                       <div class='input-group date'>
                                           {!! Form::date('createdAtFrom', Request::session()->get('User.createdAtFrom') ?? null, ['id' => 'createdAtFrom', 'class' => 'form-control datepicker', 'data-date-format' => 'yyyy-mm-dd', 'placeholder' => 'Date from...']) !!}
                                        </div>
                                    </div>
                                    <div class='form-group'>
                                        <label for="createdAtTo" class="col-form-label text-md-right">Created at to</label>
                                        <div class='input-group date'>
                                            {!! Form::date('createdAtTo', Request::session()->get('User.createdAtTo') ?? null, ['id' => 'createdAtTo', 'class' => 'form-control datepicker', 'data-date-format' => 'yyyy-mm-dd', 'placeholder' => 'Date to...']) !!}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class='form-group'>
                                        <label for="updatedAtFrom" class="col-form-label text-md-right">Updated at
                                            from</label>
                                        <div class='input-group date'>
                                            {!! Form::date('updatedAtFrom', Request::session()->get('User.updatedAtFrom') ?? null, ['id' => 'updatedAtFrom', 'class' => 'form-control datepicker', 'data-date-format' => 'yyyy-mm-dd', 'placeholder' => 'Date from...']) !!}
                                        </div>
                                    </div>
                                    <div class='form-group'>
                                        <label for="createdAtTo" class="col-form-label text-md-right">Updated at to</label>
                                        <div class='input-group date'>
                                            {!! Form::date('updatedAtTo', Request::session()->get('User.updatedAtTo') ?? null, ['id' => 'updatedAtTo', 'class' => 'form-control datepicker', 'data-date-format' => 'yyyy-mm-dd', 'placeholder' => 'Date to...']) !!}
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class='form-group'>
                                        <label for="updatedAtFrom" class="col-form-label text-md-right">Last login at
                                            from</label>
                                        <div class='input-group date'>
                                            {!! Form::date('lastLoginAtFrom', Request::session()->get('User.lastLoginAtFrom') ?? null, ['id' => 'lastLoginAtFrom', 'class' => 'form-control datepicker', 'data-date-format' => 'yyyy-mm-dd', 'placeholder' => 'Date from...']) !!}
                                        </div>
                                    </div>
                                    <div class='form-group'>
                                        <label for="createdAtTo" class="col-form-label text-md-right">Last login at to</label>
                                        <div class='input-group date'>
                                            {!! Form::date('lastLoginAtTo', Request::session()->get('User.lastLoginAtTo') ?? null, ['id' => 'lastLoginAtTo', 'class' => 'form-control datepicker', 'data-date-format' => 'yyyy-mm-dd', 'placeholder' => 'Date to...']) !!}
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="row justify-content-center">
                                <button type="submit" class="btn btn-success">Filter</button>
                            </div>
                        </form>
                        <form action="{{ route('admin.users.clearFilters')}}" method="post">
                            <div class="row justify-content-center">
                                <input type="submit" class="btn btn-success btn-sm" value="Clear filter"/>
                            </div>
                            @method('post')
                            @csrf
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-11">
                <div class="card">
                    <div class="card-header">Users</div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif
                        @if (session('error'))
                            <div class="alert alert-danger" role="alert">
                                {{ session('error') }}
                            </div>
                        @endif

                        <table class='table'>
                            <thead>
                            <tr>
                                <th scope="col">ID</th>
                                <th colspan="1">Name</th>
                                <th colspan="1">Email</th>
                                <th colspan="1">Status</th>
                                <th colspan="1">Created at</th>
                                <th colspan="1">Updated at</th>
                                <th colspan="1">Deleted at</th>
                                <th colspan="1">Last login at</th>
                                <th colspan="1">Actions</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($users as $user)
                                @php $deleted = $user->deleted_at; @endphp
                                <tr @if($deleted) class='bg-danger'
                                    @elseif($user->active === 1) class='bg-light' @endif>
                                    <td>{{$user->id}}</td>
                                    <td>{{$user->name}}</td>
                                    <td>{{$user->email}}</td>
                                    <td> @if($user->active === 1) Aktywny @else Nieaktywny @endif</td>
                                    <td>{{$user->created_at}}</td>
                                    <td>{{$user->updated_at}}</td>
                                    <td>{{$user->deleted_at}}</td>
                                    <td>{{$user->lastlogin_at}}</td>
                                    <td>
                                        @if(!$deleted)
                                            <a href="{{ route('admin.users.edit', $user)}}">
                                                <button type="button" class="btn btn-success btn-sm float-left">Edit
                                                </button>
                                            </a>
                                            <form action="{{route('admin.users.softDelete', $user)}}" method="post">
                                                <input type="submit" class="btn btn-danger btn-sm" value="Soft delete"/>
                                                @method('delete')
                                                @csrf
                                            </form>
                                        @endif
                                        <form action="{{route('admin.users.destroy', $user)}}" method="post">
                                            <input type="submit" class="btn btn-warning btn-sm" value="Hard Delete"/>
                                            @method('delete')
                                            @csrf
                                        </form>
                                        @if($deleted)
                                            <form action="{{ route('admin.users.restore', $user )}}" method="post">
                                                <input type="submit" class="btn btn-success btn-sm" value="Restore"/>
                                                @method('put')
                                                @csrf
                                            </form>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
                        {{ $users->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

<style>
    tr.blue td {
        font-color: #ADD8E6;
    }
</style>